### ISSUE TITLE
position info wrong in case of unicode characters

### ISSUE THREAD

**Issue by AlexHaxe** [Simn/hxparse#41] opened 2015-12-03 00:13 UTC
When using HaxeLexer 1.0.0 and hxparse 4.0.0 the token positions are incorrect. Positions are correct when switching back to hxparse 3.0.0.
Sample file (test.hx):
```haxe
/*
* üä
*/
class Test {
  public function new ()
  {}
}
```
output with hxparse 3.0.0:
```
Comment(* üä)                         { file => test.hx, max => 12, min => 0 }
Kwd(KwdClass)                         { file => test.hx, max => 18, min => 13 }
    Const(CIdent(Test))               { file => test.hx, max => 23, min => 19 }
        BrOpen                        { file => test.hx, max => 25, min => 24 }
            Kwd(KwdPublic)            { file => test.hx, max => 34, min => 28 }
            Kwd(KwdFunction)          { file => test.hx, max => 43, min => 35 }
                Kwd(KwdNew)           { file => test.hx, max => 47, min => 44 }
                    POpen             { file => test.hx, max => 49, min => 48 }
                        PClose        { file => test.hx, max => 50, min => 49 }
                    BrOpen            { file => test.hx, max => 54, min => 53 }
                        BrClose       { file => test.hx, max => 55, min => 54 }
            BrClose                   { file => test.hx, max => 57, min => 56 }
```
output with hxparse 4.0.0:
```
Comment(* üä)                         { file => test.hx, max => 16, min => 0 }
Kwd(KwdClass)                         { file => test.hx, max => 22, min => 17 }
    Const(CIdent(Test))               { file => test.hx, max => 27, min => 23 }
        BrOpen                        { file => test.hx, max => 29, min => 28 }
            Kwd(KwdPublic)            { file => test.hx, max => 38, min => 32 }
            Kwd(KwdFunction)          { file => test.hx, max => 47, min => 39 }
                Kwd(KwdNew)           { file => test.hx, max => 51, min => 48 }
                    POpen             { file => test.hx, max => 53, min => 52 }
                        PClose        { file => test.hx, max => 54, min => 53 }
                    BrOpen            { file => test.hx, max => 58, min => 57 }
                        BrClose       { file => test.hx, max => 59, min => 58 }
            BrClose                   { file => test.hx, max => 61, min => 60 }
```
you can see the positions from hxparse 4.0.0 are higher starting with the unicode comment. 
The numbers go higher with every additional unicode character used.

I am testing on a 64bit linux system (if that makes any difference).

**Comment by Simn** [comment] 2015-12-03 07:59
I hope this wasn't caused by #35.

cc @mandel59

**Comment by mandel59** [comment] 2015-12-03 10:38
haxe.Utf8.decode should be deprecated. It “decodes” to Latin-1, which can not represent Unicode strings.

**Comment by mandel59** [comment] 2015-12-03 10:43
haxe.io.Bytes.ofString already (re)encodes platform-native strings to UTF-8, so there should be no need to modify ByteData.

**Comment by mandel59** [comment] 2015-12-03 12:51
@AlexHaxe What code reproduces the result?

**Comment by AlexHaxe** [comment] 2015-12-03 13:32
I have uploaded a small testcase to https://github.com/AlexHaxe/haxe-checkstyle.git, switch to  `hxparse_position` branch and use `buildPositionTest.hxml` to run it. The testcase itself is located in `TokenTest.hx`.

Output is generated by an experimental token tree builder for haxe-checkstyle that generates a searchable tree of all tokens from HaxeLexer (of haxeparser).
I used that to print out the tokens for both cases and see the differences. I have slightly reformatted the output of the token tree to make it easier to read in my first post, actual output looks a bit different.

**Comment by AlexHaxe** [comment] 2015-12-03 14:36
I have updated my test case, the old version printed out token positions that were calculated by visiting all childs. The current version uses just the pos info from HaxeLexer for each token.

**Comment by mandel59** [comment] 2015-12-03 14:59
with hxparse 4.0.0
```
/Users/ryama/tree/haxe-checkstyle/TokenTest.hx:38: 
  Kwd(KwdClass)				{ file => test.hx, max => 23, min => 18 }
      Const(CIdent(Test))				{ file => test.hx, max => 28, min => 24 }
          Comment(
* üä
)				{ file => test.hx, max => 17, min => 1 }
          BrOpen				{ file => test.hx, max => 30, min => 29 }
              Kwd(KwdFunction)				{ file => test.hx, max => 48, min => 40 }
                  Kwd(KwdNew)				{ file => test.hx, max => 52, min => 49 }
                      Kwd(KwdPublic)				{ file => test.hx, max => 39, min => 33 }
                      POpen				{ file => test.hx, max => 54, min => 53 }
                          PClose				{ file => test.hx, max => 55, min => 54 }
                      BrOpen				{ file => test.hx, max => 59, min => 58 }
                          BrClose				{ file => test.hx, max => 60, min => 59 }
              BrClose				{ file => test.hx, max => 62, min => 61 }
```

with hxparse development branch
```
/Users/ryama/tree/haxe-checkstyle/TokenTest.hx:38: 
  Kwd(KwdClass)				{ file => test.hx, max => 19, min => 14 }
      Const(CIdent(Test))				{ file => test.hx, max => 24, min => 20 }
          Comment(
* üä
)				{ file => test.hx, max => 13, min => 1 }
          BrOpen				{ file => test.hx, max => 26, min => 25 }
              Kwd(KwdFunction)				{ file => test.hx, max => 44, min => 36 }
                  Kwd(KwdNew)				{ file => test.hx, max => 48, min => 45 }
                      Kwd(KwdPublic)				{ file => test.hx, max => 35, min => 29 }
                      POpen				{ file => test.hx, max => 50, min => 49 }
                          PClose				{ file => test.hx, max => 51, min => 50 }
                      BrOpen				{ file => test.hx, max => 55, min => 54 }
                          BrClose				{ file => test.hx, max => 56, min => 55 }
              BrClose				{ file => test.hx, max => 58, min => 57 }
```

It seems the current development branch works well.

**Comment by Simn** [comment] 2015-12-03 15:04
Right, I merged your PR _after_ I made the haxelib release because I wanted it to be compatible with Haxe versions < 3.2.

**Comment by Simn** [comment] 2015-12-03 15:07
I have overwritten the 4.0.0 release on haxelib. It's a major version change so it's alright if it's not compatible.

**Closed by Simn** 2015-12-03 15:07 UTC
